### ISSUE TITLE
discrepencies in cell positioning

### ISSUE THREAD

**Issue by votbot420** [sebsebmc/starlink-coverage#26]
Noticing quite a large discrepancy amongst cells between your map and the starlink.com/map could you advise?

**Comment by sebsebmc** [comment]
Hah, starlink.com/map is something that didn't exist when I wrote my version. I also haven't updated my data for over a year and a half at this point. (Yeah, I never automated the process because it takes nearly 30 minutes to run so I cant just do it in GitHub Actions or something like that, and as Starlink adds more satellites my code takes longer) 

It does seem like Starlink may be using H3 or they could simply be using a completely different hex-based grid system. H3 supports different levels of cell sizes and they mathematically cant perfectly cover a larger cell at the next level down (you can see this when you double click a cell to see the cells covered in the higher resolution level). Their graph appears to be based on a much smaller resolution than I had (probably 2 or 3 levels higher) which drastically increases the time it takes to run my simulation.

**Comment by sebsebmc** [comment]
My code also assumes there's always a basestation in sight of all Starlink satellites. Obviously, Starlink themselves is only showing a graph where they provide service, whereas my simulation shows where there satellites _could_ have provided service when I ran the simulation.
