### ISSUE TITLE
Help: 'failures_url' seems outdated...

### ISSUE THREAD

**Issue by kgtjan** [sebsebmc/starlink-coverage#27]
In the main.py the failures_url link seems not working.  There are a few URL redirects and it seems the data is not downloaded.  Here is the output when I run the main.py:

Loaded 2568 satellites
Traceback (most recent call last):
File "main.py", line 201, in
op_sats = filter_sats(sats)
File "main.py", line 61, in filter_sats
name = row{'NAME'].strip()
KeyError: 'NAME'

Could  you let me know how to fix this problem?
Thanks a lot for sharing the code and thanks for your support.

Thanks!!

**Comment by kgtjan** [comment]
BTW here is the output when I run the main.py:

Loaded 2568 satellites
Traceback (most recent call last):
File "main.py", line 201, in <module>
   op_sats = filter_sats(sats)
File "main.py", line 61, in filter_sats
   name = row{'NAME'].strip()
KeyError: 'Name'


Thanks.

**Comment by sebsebmc** [comment]
Unfortunately, the list of failed satellites that I used before is no longer maintained and I no longer have access to the data. The data was previously provided by another Starlink visualization tool author (see context here: https://www.reddit.com/r/Starlink/comments/hc6jus/a_daily_coverage_map_for_starlink/fvglhot/?context=3 )

Before I used this curated list of failed satellites, I just approximated which satellites were operational based on altitude but the issue is that as more satellites were added some were at different shells heights so the approximation began to fail. We can go back to a more conservative system where satellites below a certain altitude are not considered functional but will introduce a little bit of error. 

I don't believe Starlink provides information about which satellites have failed and are being decommissioned anyways so its just been based on observations by observers anyways.

**Comment by kgtjan** [comment]
Thanks for the info!
BTW when I run the simulation, it generates a file "h3_4_cov_0.txt" is generated, and each line has two numbers separated by a comma, such as:
    8457507ffffffff,349

Could you explain what information those two numbers carry?

Thanks again!!

**Comment by kgtjan** [comment]
I've figured out the output.  Thanks!

**Comment by sebsebmc** [comment]
Leaving this here in case others would benefit, the 2 numbers are the H3 cell id and the minutes of satellite coverage per day.

**Comment by kgtjan** [comment]
Thanks for quick response.  
I commented out the portion that initializes the list with failed sats.   The main.py does not return errors, but it just creates a data file, not displaying any figure or plots.  Is it normal?

Thanks again. 
Keith
